services:
  limesurvey:
    build:
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # TODO Update storage location as desired
      - surveys:/var/www/html/upload/surveys
    networks:
      - limesurvey-db
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=lime-db"
      # TODO set passwords
      # - "DB_PASSWORD="
      # - "ADMIN_PASSWORD="
      # If you require an empty table prefix, use a space as the DB_TABLE_PREFIX
      # - "DB_TABLE_PREFIX= "
  lime-db:
    image: docker.io/mariadb:11.4
    networks:
      - limesurvey-db
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      # TODO set passwords
      # - "MYSQL_PASSWORD="
      # - "MYSQL_ROOT_PASSWORD="

volumes:
  surveys:

networks:
  limesurvey-db:
    driver: bridge
